### ISSUE TITLE
Prebuilt StitchImage.apk includes Firebase Analytics and other Google spyware

### ISSUE THREAD

**Issue by Terminator-J** [crdroidandroid/android_external_asus_stitchimage#4]
So I know we want long screenshots, I do too. I get it. 

A lot of folks are using crDroid because it allows you to run either microG as a Google replacement, or go entirely free of a GMS implementation (but with actual customization & features, unlike LineageOS). Myself included. 

Having a built-in ROM side app that includes Firebase analytics and G Play Store tracking really goes against that. Is there any good way to reverse the apk and strip that out?

![Screenshot from 2021-05-02 10-08-35](https://user-images.githubusercontent.com/34873300/116821343-6669ff00-ab2e-11eb-9e1e-f641abc36a42.png)

**Comment by neobuddy89** [comment]
I have disabled FireBase and google receivers in AndroidManifest.xml - believe that should do the job. Tested apk, works fine.

https://github.com/crdroidandroid/android_external_asus_stitchimage/commit/9bf8a6f10bca512d2afc4198dfec3a377af72f21
